### ISSUE TITLE
改善 spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md

### ISSUE THREAD

**Issue by guoxiangzhou** [zilliztech/arctern-docs#39]
- 是否arctern-resources有版本设置
![6](https://user-images.githubusercontent.com/52496626/81276189-428fec80-9085-11ea-9461-f45c35677bd5.png)

- $SPARK_HOME和$CONDA_HOME容易让用户理解为环境变量，实际上是自定义安装路径
![1](https://user-images.githubusercontent.com/52496626/81276304-681cf600-9085-11ea-84eb-19df3b3542cb.png)
![2](https://user-images.githubusercontent.com/52496626/81276315-6a7f5000-9085-11ea-8bcb-fdec832d5efb.png)

- 按照当前的步骤安装，在进行安装验证时提示如下错误
![3](https://user-images.githubusercontent.com/52496626/81276408-897de200-9085-11ea-9985-64475b494cd3.png)
错误显示如下：
![4](https://user-images.githubusercontent.com/52496626/81276422-8d116900-9085-11ea-9ecd-892fa211d81d.png)

- 上面采用的虚拟环境名字是arctern-spark，下面配置里面又是arctern，有歧义
![7](https://user-images.githubusercontent.com/52496626/81276530-b92cea00-9085-11ea-96bf-d7533175baca.png)

**Comment by beautifulpython** [comment]
PR #78 fixes some of the issues mentioned above. 
According to the operation of the document, I did not duplicate the `ImportError` locally. @guoxiangzhou

**Comment by yxm1536** [comment]
Fixed in PR #78
