### ISSUE TITLE
改善/restful/webserver_installation_config.md

### ISSUE THREAD

**Issue by guoxiangzhou** [zilliztech/arctern-docs#40]
采用pip方式安装arctern_server, 启动时提示如下错误：
![12](https://user-images.githubusercontent.com/52496626/81364025-40766e00-9117-11ea-97ee-106f303c6eb2.png)

**Comment by guoxiangzhou** [comment]
建议把config.ini中的地址，默认写成local模式，localhost:7077

**Comment by guoxiangzhou** [comment]
出现错误的原因，应该是打包的arctern-server没有安装所有的依赖包

**Comment by DragonDriver** [comment]
fixed by [pr 574 of arctern](https://github.com/zilliztech/arctern/pull/574).
