### ISSUE TITLE
修改restful/restful_quick_start.md

### ISSUE THREAD

**Issue by guoxiangzhou** [zilliztech/arctern-docs#41]
r = requests.post(url="http://127.0.0.1:8080/scope", headers={"Content-Type": "application/json"}, data=payload)
改为
r = requests.post(url="http://127.0.0.1:8080/scope", headers={"Content-Type": "application/json"}, json=payload)

即 data=payload 改为 json=payload

按照文档中的步骤，并未生成对应的图片

目前基于pip安装的arctern-server是不能直接运行的，会提示各种依赖没有

**Comment by guoxiangzhou** [comment]
所有的 data=payload 改为 json=payload

**Comment by DragonDriver** [comment]
fixed by [pr 75](https://github.com/zilliztech/arctern-docs/pull/75) and [pr 574 of arctern](https://github.com/zilliztech/arctern/pull/574).
