### ISSUE TITLE
restful/api/function/create_scope.md

### ISSUE THREAD

**Issue by guoxiangzhou** [zilliztech/arctern-docs#44]
文档中描述，失败时
{
    "status": "error",
    "code": "-1",
    "message": "scope already exist!"
}

实际测试，显示：
{
     "code":-1,
     "message": "sorry, scope_id exists!",
     "status": "error"
}

**Comment by DragonDriver** [comment]
fixed by [pr 574 of arctern](https://github.com/zilliztech/arctern/pull/574).
