### ISSUE TITLE
change ，to ,

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#51]
branch : 0.1.x
doc : doc-cn/source/python/data_source/geometry_data_format.md

```python
>>> valid_data.to_csv("geos.csv"，index=None,sep='|')
  File "<stdin>", line 1
    valid_data.to_csv("geos.csv"，index=None,sep='|')
                                      ^
SyntaxError: invalid character in identifier
```

**Comment by become-nice** [comment]
> branch : 0.1.x
> doc : doc-cn/source/python/data_source/geometry_data_format.md
> 
> ```python
> >>> valid_data.to_csv("geos.csv"，index=None,sep='|')
>   File "<stdin>", line 1
>     valid_data.to_csv("geos.csv"，index=None,sep='|')
>                                       ^
> SyntaxError: invalid character in identifier
> ```

The reason of this bug is that column name 'geos' has extra space .
