### ISSUE TITLE
Conda environment name is inconsistent.

### ISSUE THREAD

**Issue by czs007** [zilliztech/arctern-docs#53]
branch: 0.1.x
doc : doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md

For instance, in the section of  `## 配置 Spark 的 Python 路径`,  the following contents

```
spark.executorEnv.PROJ_LIB [path/to/your/conda]/envs/arctern/share/proj
spark.executorEnv.GDAL_DATA [path/to/your/conda]/envs/arctern/share/gdal
```
should replace `arctern` with `arctern_spark`,  since the environment  we created before is `arctern_spark`.

**Comment by become-nice** [comment]
> branch: 0.1.x
> doc : doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
> 
> For instance, in the section of `## 配置 Spark 的 Python 路径`, the following contents
> 
> ```
> spark.executorEnv.PROJ_LIB [path/to/your/conda]/envs/arctern/share/proj
> spark.executorEnv.GDAL_DATA [path/to/your/conda]/envs/arctern/share/gdal
> ```
> 
> should replace `arctern` with `arctern_spark`, since the environment we created before is `arctern_spark`.

I have change this markdown, please check arctern-docs again.
