### ISSUE TITLE
Typo in quick-start-pandas.md

### ISSUE THREAD

**Issue by shengjh** [zilliztech/arctern-docs#54]
Branch: 0.1.x

https://github.com/zilliztech/arctern-docs/blob/branch-0.1.x/doc-cn/source/python/quick_start/quick-start-pandas.md#%E5%8A%A0%E8%BD%BD%E6%95%B0%E6%8D%AE
加载数据这部分， schema拼写错误
```
nyc_schame={
...     "VendorID":"string",
...     "tpep_pickup_datetime":"string",
```

**Comment by yxm1536** [comment]
Fixed in PR #99
