### ISSUE TITLE
Failed to run spark_udf_ex.py

### ISSUE THREAD

**Issue by czs007** [zilliztech/arctern-docs#56]
branch: 0.1.x
doc : doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md

The test failed, as the input and output of some functions have changed.

**Comment by become-nice** [comment]
> branch: 0.1.x
> doc : doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
> 
> The test failed, as the input and output of some functions have changed.

I have fix it ,please check.
