### ISSUE TITLE
ST_GeomFromGeoJSON api

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#58]
https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/python/api/geospatial/function/geospatial/ST_GeomFromGeoJSON.html
```python
>>> import arctern
>>> import pandas
>>> data = pandas.Series(["{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}"])
  File "<stdin>", line 1
    data = pandas.Series(["{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}"])
                                ^
SyntaxError: invalid syntax

```

**Comment by become-nice** [comment]
> https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/python/api/geospatial/function/geospatial/ST_GeomFromGeoJSON.html
> 
> ```python
> >>> import arctern
> >>> import pandas
> >>> data = pandas.Series(["{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}"])
>   File "<stdin>", line 1
>     data = pandas.Series(["{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}"])
>                                 ^
> SyntaxError: invalid syntax
> ```

Please retry it later.
