### ISSUE TITLE
" change to '''

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#64]
https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/api/geospatial/function/geospatial/Spark_ST_GeomFromGeoJSON.html

```python
>>> test_data = []
>>> test_data.extend([("{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}",)])
  File "<stdin>", line 1
    test_data.extend([("{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}",)])
                             ^
SyntaxError: invalid syntax

```

**Comment by become-nice** [comment]
> https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/api/geospatial/function/geospatial/Spark_ST_GeomFromGeoJSON.html
> 
> ```python
> >>> test_data = []
> >>> test_data.extend([("{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}",)])
>   File "<stdin>", line 1
>     test_data.extend([("{"type":"LineString","coordinates":[[1,2],[4,5],[7,8]]}",)])
>                              ^
> SyntaxError: invalid syntax
> ```

When create html file, ' \"type\" ' becomes ' "type" ', maybe I should replace ' "type" ' to ' \"type\" ' in html file.

**Comment by beautifulpython** [comment]
I recommend using python '''some-strings...''' to avoid the trouble of transferring characters.

**Comment by become-nice** [comment]
> I recommend using python '''some-strings...''' to avoid the trouble of transferring characters.

I don't understand what you suggest, but I replace this string in html.

**Comment by become-nice** [comment]
> I recommend using python '''some-strings...''' to avoid the trouble of transferring characters.

I have fix it in pr 108, please retry it.
