### ISSUE TITLE
ST_DistanceSphere error

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#67]
https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/api/geospatial/function/geospatial/Spark_ST_DistanceSphere.html

```python
    raise converted
pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;
```

**Comment by beautifulpython** [comment]
I'm not sure if it's because of my local environment.(python interface test is ok.)

**Comment by become-nice** [comment]
> I'm not sure if it's because of my local environment.(python interface test is ok.)

After conda install libarctern ,arctern, arctern-spark, i can run it normal. I think your enviroment is wrong.
